version: '3.8'

services:
  # Context7 MCP Server
  context7-mcp:
    image: node:18-alpine
    container_name: context7-mcp-server
    ports:
      - "4001:4000"
    environment:
      - MCP_SERVER_ID=context7-mcp
      - COORDINATOR_URL=http://localhost:9000
      - REDIS_URL=redis://localhost:6379
    volumes:
      - ./scripts:/scripts
    command: >
      sh -c "
      npm init -y &&
      npm install express cors &&
      node /scripts/context7-server.js
      "
    restart: unless-stopped
    
  # Enhanced Copilot MCP Server  
  enhanced-copilot-mcp:
    image: node:18-alpine
    container_name: enhanced-copilot-mcp-server
    ports:
      - "4002:4000"
    environment:
      - MCP_SERVER_ID=enhanced-copilot-mcp
      - COORDINATOR_URL=http://localhost:9000
    volumes:
      - ./scripts:/scripts
    command: >
      sh -c "
      npm init -y &&
      npm install express cors &&
      node /scripts/copilot-server.js
      "
    restart: unless-stopped
    
  # Price Oracle MCP Server
  price-oracle-mcp:
    image: node:18-alpine
    container_name: price-oracle-mcp-server
    ports:
      - "4007:4000"
    environment:
      - MCP_SERVER_ID=price-oracle-mcp
      - COORDINATOR_URL=http://localhost:9000
    volumes:
      - ./scripts:/scripts
    command: >
      sh -c "
      npm init -y &&
      npm install express cors axios &&
      node /scripts/oracle-server.js
      "
    restart: unless-stopped
